version: 2.1

orbs:
  rpmbuild: aursu/rpmbuild@<<pipeline.parameters.dev-orb-version>>
  circleci-cli: circleci/circleci-cli@0.1.8
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-tests-for-rpmbuild:
    executor: cli/default
    steps:
      - checkout

workflows:
  integration-tests_prod-release:
    jobs:
      - integration-tests-for-rpmbuild
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          filters:
            branches:
              only: master
          orb-name: aursu/rpmbuild
          publish-version-tag: false
          requires:
            - integration-tests-for-rpmbuild
    when: << pipeline.parameters.run-integration-tests >>
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: aursu/rpmbuild
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
