description: >
  Build RPM packages and upload them into Bintray

parameters:
  build_file:
    type: string
    default: "docker-compose.yml"
    description: >
      Docker Compose file to use for build image building

  build_service:
    type: string
    description: >
      Docker Compose service inside provided build_file Docker Compose config

  bintray_uploader:
    type: string
    description: >
      Docker service to use in order to upload RPM packages into BinTray

  bintray-repo:
    type: string
    default: $BINTRAY_REPO
    description: >
      BinTray repository to upload RPM packages into

  artifactory-url:
    type: env_var_name
    default: ARTIFACTORY_URL
    description: Artifactory instance URL

executor:
  name: default

environment:
  ARTIFACTORY_URL: << parameters.artifactory-url >>

steps:
  - git
  - build:
      file: << parameters.build_file >>
      service: << parameters.build_service >>
  - rpm:
      file: << parameters.build_file >>
      service: << parameters.build_service >>
  - bintray:
      bintray-repo: << parameters.bintray-repo >>
      uploader: << parameters.bintray_uploader >>
