description: >
  CentOS RPM and Docker rpmbuild images build environment

machine:
  image: ubuntu-2004:202201-02

environment:
  OS7: "7.9.2009"
  OS8: stream8
  OS9: stream9-20221206.0
  RL8: "8.6.20227707"
  RL9: "9.0.20220720"
  OS7TAG: "7.9.2009"
  OS8TAG: stream8
  OS9TAG: stream9-20221206.0
  RL8TAG: "8"
  RL9TAG: "9"
