description: >
  CentOS RPM and Docker rpmbuild images build environment

machine:
  image: ubuntu-2004:202201-02

environment:
  OS7: "7.9.2009"
  OS8: stream8
  OS7TAG: "7.9.2009"
  OS8TAG: stream8
